---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false

  vars: 
    nested_roles: "{{ max_nested_import_roles | default(40) | int }}"

  tasks:
    - include_role:
        name: use_import_role
      vars:
        final_role: false
      loop_control:
        loop_var: roleidx
      with_sequence: "start=1 end={{(nested_roles|int)-1|int}}"

    - include_role:
        name: use_import_role
      vars:
        final_role: true
        roleidx: "{{ nested_roles }}"

  handlers: []
