---
# tasks file for roles/create_arbo
- file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/home/riton/Desktop/poc_ansible_recurse/roles/r{{roleidx}}"
    - "/home/riton/Desktop/poc_ansible_recurse/roles/r{{roleidx}}/tasks"

- template:
    src: 'main.yml.j2'
    dest: "/home/riton/Desktop/poc_ansible_recurse/roles/r{{roleidx}}/tasks/main.yml"
  when: not final_role

- template:
    src: 'final-main.yml.j2'
    dest: "/home/riton/Desktop/poc_ansible_recurse/roles/r{{roleidx}}/tasks/main.yml"
  when: final_role
